import Head from 'next/head'
import WeCann from './components/Home/WeCann'

export default function Home() {
  return (
    <>
      <Head>
        <title>WeCann: Innovación y redes para la industria del cannabis en Argentina.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <WeCann />
    </>
  )
}
