import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WeCann: Innovación y redes para la industria del cannabis en Argentina.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="max-w-7xl mx-auto p-4">
        <h1 className="text-4xl font-bold">WeCann</h1>
      </div>
    </div>
  )
}